monitor.libcamera.rules = [
  {
    matches = [
      {
        api.libcamera.sp7.profile = "hq"
      }
    ]
    actions = {
      update-props = {
        node.name        = "sp7.rear.hq"
        node.nick        = "Surface Rear HQ"
        node.description = "Surface Rear HQ"
      }
    }
  }
  {
    matches = [
      {
        api.libcamera.sp7.profile = "smooth"
      }
    ]
    actions = {
      update-props = {
        node.name        = "sp7.rear.smooth"
        node.nick        = "Surface Rear Smooth"
        node.description = "Surface Rear Smooth"
      }
    }
  }
  {
    matches = [
      {
        api.libcamera.sp7.profile = "fast"
      }
    ]
    actions = {
      update-props = {
        node.name        = "sp7.rear.fast"
        node.nick        = "Surface Rear Fast"
        node.description = "Surface Rear Fast"
      }
    }
  }
]
